### ISSUE TITLE
Commit 5c835a05 breaks Makefile

### ISSUE THREAD

**Issue by ragle** [saltares/glapse#10]
Firstly - this project is great. I used it in the past via the deb package and really enjoyed it. Thank you very much! 

I'm building from source now to take advantage of the avconv switchover and found a problem. 

It looks like [5c835a05](https://github.com/saltares/glapse/commit/5c835a05c375ac6ee3ca96322f7a35e6a82f5cff) breaks the makefile. 

Specifically, [using a relative include](https://github.com/saltares/glapse/blob/master/glapseControllers/configuration.py#L16) instead of the [absolute path](https://github.com/saltares/glapse/blob/master/glapseControllers/configuration.py#L11) where the [Makefile puts images and .glade files](https://github.com/saltares/glapse/blob/master/makefile#L22,L24) causes problems when [setting the path to load these resources here](https://github.com/saltares/glapse/blob/master/glapseGUI/glapseGUI.py#L47). 

Then, the error you get when you try to run glapse of course is: 

python
```
Traceback (most recent call last):
  File "glapse.py", line 88, in <module>
    main()
  File "glapse.py", line 80, in main
    glapse = glapseGUI.GlapseMainGUI()
  File "/usr/lib/glapse/glapseGUI/glapseGUI.py", line 50, in __init__
    builder.add_from_file(path)
glib.GError: Failed to open file '/usr/lib/glapse/data/glade/glapseGUI.glade': No such file or directory
```

Seems the options are: 

1) Respect absolute paths specified in the Makefile

2) update the makefile to put resources in `/usr/lib/glapse/data/img` and `/usr/lib/glapse/data/glade/` and stick with the relative include

Let me know which you think is best in terms of the rest of the codebase and I'm happy to submit a pull request.

Cheers!

**Comment by saltares** [comment]
Hi @ragle!

It's great you like the project and that it's been useful to you. I made it many years ago back when I was at uni to learn Python and never thought anybody would actually use it. Now I realise some people have!

That code you're linking to was a horrible hack, it's great you're willing to fix it. I think it's best if we stick to relative paths and make the makefile put everything into `/usr/lib/glapse/...`.

I would really appreciate it if you sent a PR for it!

Thanks :-).

**Comment by ragle** [comment]
> I made it many years ago back when I was at uni
> That code you're linking to was a horrible hack

Every repo I have in my account is this, haha. Just glad I could help. PR submitted!
